[Bug] Fixed bug where typing the user name quickly would crash the app.
kevin-ghannoum/soen490 pull request #238
Opened 2022-03-15 23:06 UTC by Manraj45

closes #237 

Cause:
When calling an API, the endpoint verifies that the user trying to access the endpoint has the appropriate role. The role is fetched by the auth0 API. When typing quickly the name of the user, this generated a lot of request to the auth0 API. This caused the app to crash since auth0 blocked the requests.
Fix:
Instead of calling the auth0 API each time to get the role of the user, save the role in the JWT token. This fixed the issue.
Screenshot:
![image](https://user-images.githubusercontent.com/48056716/158486210-ed0fa070-494f-4743-8294-636d6f76ae33.png)

2022-03-15 23:45 UTC, kevin-ghannoum requested changes
Good fix! However, change the prefix of the PR to PATCH.

2022-03-15 23:59 UTC, Manraj45 commented
> Good fix! However, change the prefix of the PR to PATCH.

Done

2022-03-16 01:30 UTC, kevin-ghannoum approved these changes

2022-03-16 19:31 UTC, Mnx458 approved these changes
Nice so now we can make multiple requests without failing.

2022-03-16 19:34 UTC, merged