[MAJOR] Created project financials page.
kevin-ghannoum/soen490 pull request #244
Opened 2022-03-21 23:29 UTC by kevin-ghannoum

closes #203

2022-03-23 18:02 UTC, Manraj45 requested changes
Need to rework the backend a bit and change the endpoints for the backend and frontend.

2022-03-23 18:02 UTC, Manraj45 commented on backend/src/main/routes/TransactionRoute.ts
> +      .get(async (req: express.Request, res: express.Response, next: express.NextFunction) => {
Most of the time, in the route, you should only be calling the service methods. In rare cases, you can have logic in the route.

2022-03-23 18:39 UTC, Mnx458 commented on backend/src/main/routes/TransactionRoute.ts
> +      .get(async (req: express.Request, res: express.Response, next: express.NextFunction) => {
I moved all the logic in transactionService

2022-03-23 18:40 UTC, Mnx458 commented on frontend/src/App.tsx
> +                            <Financials id="1" />
That was a mistake

2022-03-23 19:19 UTC, Mnx458 commented
![image](https://user-images.githubusercontent.com/36893250/159779099-65502924-5485-4192-b178-3ae2841ee63a.png)
![image](https://user-images.githubusercontent.com/36893250/159779130-72fc5496-3753-43cf-8efe-30ffd408ea06.png)

2022-03-23 20:15 UTC, jmezaber commented
> ![image](https://user-images.githubusercontent.com/36893250/159779099-65502924-5485-4192-b178-3ae2841ee63a.png) ![image](https://user-images.githubusercontent.com/36893250/159779130-72fc5496-3753-43cf-8efe-30ffd408ea06.png)

The UI is lacking a bit of colour. The mockup had colours for the table headers, it would be nice if that can be reflected in the UI. 

Also, if a project has an amount of 0$, it shouldn't appear in the table. The legend inside the pie chart is not aligned. 

I was also wondering if the page is responsive and where does the pie chart appear on the page?

2022-03-23 21:22 UTC, nasaku898 commented on backend/src/main/services/TransactionService.ts
> +        console.log(element.dataValues.type);
remove console.log

2022-03-23 21:22 UTC, Manraj45 requested changes
Remove console log

2022-03-23 21:22 UTC, Manraj45 commented on backend/src/main/services/TransactionService.ts
> +        console.log(element.dataValues.type);
Remove console.log

2022-03-25 04:11 UTC, jmezaber requested changes
Please bring the changes to the UI mentioned in my previous comment

2022-03-28 00:28 UTC, Manraj45 commented
> Please bring the changes to the UI mentioned in my previous comment

I implemented the changes you requested. Here is the new UI:

![image](https://user-images.githubusercontent.com/48056716/160307998-564e8466-406c-40db-b1d8-ae3aa47e084f.png)
![image](https://user-images.githubusercontent.com/48056716/160308008-544893eb-dd2f-48bb-a004-aec0e089c962.png)

I also made the frontend more responsive:
![image](https://user-images.githubusercontent.com/48056716/160308044-37342567-4ad6-4604-a3af-2b452d42e1aa.png)

2022-03-28 00:45 UTC, nasaku898 commented
I like the new UI changes @Manraj45 . Great work!

2022-03-28 00:46 UTC, jmezaber approved these changes
Thanks, @Manraj45 for the UI changes, it looks beautiful!

2022-03-28 01:00 UTC, huangs08 commented
The UI changes look great! Good job.

2022-03-28 01:00 UTC, huangs08 approved these changes

2022-03-28 01:03 UTC, Manraj45 approved these changes
Good Job @Mnx458! The backend is good now.

2022-03-28 22:42 UTC, merged